micronaut:
  server:
    context-path: /template
  application:
    name: template
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  health:
    enabled: true
    sensitive: false

micrometer:
  metrics:
    enabled: true
    export:
      cloudwatch:
        enabled: true
        namespace: template-service
        step: PT1M
  web:
    server:
      auto-time-requests: true

aws:
  region: us-east-1
  logs:
    group: /aws/ec2/template-service
    stream: template-${random.uuid}
