micronaut:
  server:
    context-path: /changetracker
  application:
    name: change-tracker
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

logger:
  levels:
    com.saisontechnologyintl.template.filter.XRayFilter: DEBUG
    com.saisontechnologyintl.template.config.AwsConfig: DEBUG
    com.amazonaws.xray: DEBUG

endpoints:
  health:
    enabled: true
    sensitive: false

micrometer:
  metrics:
    enabled: true
    export:
      cloudwatch:
        enabled: true
        namespace: change-tracker-service
        step: PT1M
  web:
    server:
      auto-time-requests: true

aws:
  region: us-east-1
  xray:
    enabled: true
    tracing-name: change-tracker-service
    sampling-rate: 1.0
    daemon-address: localhost:2000
    emitter:
      daemon-address: 127.0.0.1:2000
  logs:
    group: /aws/ec2/change-tracker-service
    stream: change-tracker-${random.uuid}
